########################################
# APPLICATION
########################################
spring.application.name=api-gateway
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

########################################
# REACTIVE
########################################
spring.main.web-application-type=reactive

########################################
# CORS
########################################
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

########################################
# GATEWAY DISCOVERY
########################################
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

########################################
# ROUTES
########################################

# Users
spring.cloud.gateway.routes[0].id=users-service
spring.cloud.gateway.routes[0].uri=lb://USERS-BRICKWORK
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

# Products
spring.cloud.gateway.routes[1].id=products-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCTS-BRICKWORK
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**,/api/production-logs/**,/api/raw-materials/**

# Orders
spring.cloud.gateway.routes[2].id=orders-service
spring.cloud.gateway.routes[2].uri=lb://ORDERS-BRICKWORK
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**

# Finance
spring.cloud.gateway.routes[3].id=finance-service
spring.cloud.gateway.routes[3].uri=lb://FINANCE-BRICKWORK
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/finance/**

########################################
# LOGGING
########################################
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{40} - %msg%n