package com.brickwork.finance.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

@Entity
@Table(name = "payment_transactions")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentTransaction {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false, unique = true)
    private String orderId; // Links to the orders-brickwork service

    @Column(unique = true)
    private String razorpayOrderId; // Generated by Razorpay Step 1

    @Column(unique = true)
    private String razorpayPaymentId; // Generated by Razorpay Step 2

    private Double amount;
    private String currency = "INR";

    @Enumerated(EnumType.STRING)
    private PaymentStatus status; // CREATED, SUCCESS, FAILED

    private String paymentMethod; // UPI, CARD, NET-BANKING
    private String utrNumber; // For manual NEFT/RTGS entry

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() { createdAt = LocalDateTime.now(); updatedAt = LocalDateTime.now(); }
    @PreUpdate
    protected void onUpdate() { updatedAt = LocalDateTime.now(); }

    public enum PaymentStatus { CREATED, SUCCESS, FAILED }
}