########################################
# SERVER
########################################
server.port=${SERVER_PORT:${PORT:8081}}

########################################
# DATABASE
########################################
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

########################################
# JPA
########################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

########################################
# CONNECTION POOL
########################################
spring.datasource.hikari.pool-name=ProductsPool

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

########################################
# EUREKA
########################################
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

########################################
# PUBLIC AWS HOSTNAME
########################################
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}

########################################
# ADVERTISE HTTPS
########################################
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443

########################################
# PUBLIC URLs
########################################
eureka.instance.homePageUrl=https://${EUREKA_INSTANCE_HOSTNAME}/
eureka.instance.statusPageUrl=https://${EUREKA_INSTANCE_HOSTNAME}/actuator/info
eureka.instance.healthCheckUrl=https://${EUREKA_INSTANCE_HOSTNAME}/actuator/health

########################################
# LEASE
########################################
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

########################################
# LOGGING
########################################
logging.level.root=INFO
logging.level.com.brickwork=INFO
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

########################################
# ACTUATOR
########################################
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.endpoint.health.probes.enabled=true
