########################################
# SERVER
########################################
server.port=${PORT:8761}

########################################
# EUREKA SERVER
########################################
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

########################################
# HOSTNAME
########################################
eureka.instance.hostname=${EUREKA_HOSTNAME:service-registry}

########################################
# ACTUATOR
########################################
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.endpoint.health.probes.enabled=true

########################################
# LOGGING
########################################
logging.level.root=INFO
logging.level.com.brickwork=INFO