########################################
# APPLICATION
########################################
spring.application.name=service-registry-brickwork
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

########################################
# LOGGING
########################################
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{40} - %msg%n